# Generated by Django 4.2.3 on 2023-07-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0002_remove_book_publisher_remove_book_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='bookapp/pdfs/'),
        ),
    ]
